modules/analysis/aws-batch-demo/stack.py
modules/analysis/rosbag-image-pipeline/stack.py
modules/core/aws-batch/stack.py
modules/core/mwaa/stack.py
modules/core/neptune/stack.py
modules/core/opensearch/stack.py
modules/integration/ddb-to-opensearch/stack.py
modules/integration/eks-to-opensearch/stack.py
modules/optionals/datalake-buckets/stack.py
modules/simulations/k8s-managed/stack.py

When updating some stacks to NagPackSuppression, the `applies_to = "*"` on the rule suppression was no longer valid...causing errors

correct conversion to NagPackSuppression

---

modules/core/aws-batch/modulestack.yaml

The resource permissions on the modulestack do not seem to make sense when creating a service-linked role in the modulestack.yaml.  This policy allow the deployspec to have the permissions it needs.  No where did it refer to the role `*-masterrole` needing a service linked role creation.  
I corrected the resource reference

aligning resource permisssion

---

CHANGELOG.md
manifests/aws-batch-demo/deployment.yaml
manifests/example-dev/deployment.yaml
manifests/example-prod/deployment.yaml
manifests/ros-image-demo/deployment.yaml

Currently we use the example 123456790 together with envVariable for specifying the account ID in manifests. Most users don't see that the 123456790 should be an environment variable name and mistakenly just replace the value with their account ID
- Removed the envVar resolution in example manifests and replaced with simple key: value mapping 

fix default account resolution in manifests to reduce confusion

---

manifests/ros-image-demo/docker-image-modules.yaml
modules/analysis/rosbag-image-pipeline/app.py
modules/analysis/rosbag-image-pipeline/image_dags/ros_image_pipeline.py
modules/sensor-extraction/ros-to-png/app.py
modules/sensor-extraction/ros-to-png/src/main.py
modules/sensor-extraction/ros-to-png/stack.py

*Issue #53*
https://github.com/awslabs/autonomous-driving-data-framework/issues/53
When extracting images, save a resized image of 1280x720, compatible with yolop model, 
Run detection models on resized images instead of raw images.

resize images for detection models

---

modules/mlops/kubeflow-platform/deployspec.yaml

The Kubeflow-on-AWS does not delete the `kf-ack-sm-controller-role `role when it deletes the platform, causing OIDC inconsistencies on the trust policy.  Added the deletion of this role and policies to the deployspec

delete the kf-sagemaker role manually

---

modules/sensor-extraction/ros-to-png/src/main.py

Not all resized image directories are being passed on to the object detection and lane detection jobs. This fixes the root issue.

Bug Fix: image extraction naming issue

---

CHANGELOG.md
modules/analysis/rosbag-scene-detection/infrastructure/ecs_stack.py

The name of the lambda for `StepFunctionTrigger` in `modules/analysis/rosbag-scene-detection/infrastructure/ecs_stack.py` was hitting the 64 char limit of the service...limiting the overall name.

Lambda name limit fix

---

manifests/mlops/kf-users.yaml
modules/mlops/kubeflow-users/README.md
modules/mlops/kubeflow-users/deployspec.yaml

- Allow users to deploy `kubeflow-users` module even if no KubeflwUsers are configured
- update the README in `kubeflow-users`

allowing successful deployment of users even if users not defined

---

modules/mlops/kubeflow-platform/README.md
modules/mlops/kubeflow-platform/deployspec.yaml

Adding output to the `kubeflow-platform` module to indicate the cluster it is deployed on

adding output for refernce on kubeflow-platform module

---

CHANGELOG.md
modules/workbench/cloud9/deployspec.yaml
modules/workbench/cloud9/modulestack.yaml
modules/workbench/cloud9/scripts/pre_deploy.py
modules/workbench/cloud9/stack.py

Fix issue where the parameter `CONNECTION_TYPE` if set to `CONNECT_SSM` would fail during the CDK deploy due to resources that the CDK does not create for you but expects them to be in the account in order for the instance to be created

Fix connection type ssm

---

modules/core/aws-batch/app.py
modules/core/aws-batch/stack.py

In case the manifest config skips certain compute environments, the stack itself is missing the ARNs and deployment raises an AttributeError. This fix makes queues optional and tests against None when creating
CfnOutputs. This is tested in a custom stack only relying on AWS
Fargate.

Fix deployment issue of aws batch

---

CHANGELOG.md
data/eks_dockerimage-replication/versions/1.25.yaml
data/eks_dockerimage-replication/versions/default.yaml
manifests/example-dev/core-modules.yaml
modules/core/eks/README.md
modules/core/eks/stack.py

*Issue #, if available:* ADOT add on feature in the EKS Cluster 
The PR is to add the ADOT addon in the EKS cluster. CloudWatch Metrics is an AWS monitoring solution, and OpenTelemetry is a good compliment to it, so we have both as holistic solution. 

ADOT EKS Addon

---

modules/sagemaker/sagemaker-studio/functions/sm_studio/enable_sm_projects/requirements.txt

Fix enable_sm_project function issue which was introduced by braking change in urllib3 version 2. Similar issue: https://github.com/psf/requests/issues/6443
Otherwise, error in cloudformation was raised
```
Received response status [FAILED] from custom resource. Message returned: Error: Unable to import module 'index': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_
```
Locking the version of urllib3 to be below 2.

Fix enable_sm_project function

---

.gitignore
manifests/aws-solutions/docker-image-modules.yaml
manifests/aws-solutions/integ/addf-modules.yaml
manifests/aws-solutions/integ/idf-modules.yaml
manifests/aws-solutions/integ/manifest-update.py
modules/post-processing/yolo-object-detection/app.py
modules/post-processing/yolo-object-detection/stack.py
modules/post-processing/yolop-lane-detection/app.py
modules/post-processing/yolop-lane-detection/stack.py
modules/sensor-extraction/ros-to-parquet/app.py
modules/sensor-extraction/ros-to-parquet/stack.py
modules/sensor-extraction/ros-to-png/app.py
modules/sensor-extraction/ros-to-png/stack.py

**Does not need to be merged until integration testing is finalized**
- Adds manifests used by integration testing
- Adds `removal_policy` params to modules utilizing `ecr.Repository`. Default is to Retain which will not work in integration testing as resources need to be recreated each invocation.

feat: Add support for integration testing

---

modules/analysis/rosbag-image-pipeline/coverage.ini
modules/analysis/rosbag-image-pipeline/tests/test_app.py
modules/analysis/rosbag-image-pipeline/tests/test_stack.py

Adding unit tests for `rosbag-image-pipeline` stack and app. (This PR does not include tests for `image_dags`)

Add Rosbag image pipeline stack and app tests

---

CHANGELOG.md
modules/optionals/datalake-buckets/README.md
modules/optionals/datalake-buckets/app.py
modules/optionals/datalake-buckets/stack.py
modules/optionals/datalake-buckets/tests/test_stack.py

MWAA pings the artifacts bucket every 2 seconds...and the result is an access log to the logs bucket (700kb per) that over time cause the auto-delete of the lambda to time out due to the number of files to delete when destroying.  Adding a lifecycle rule to delele logs older that 2 days old in the `artifacts-bucket-logs/` prefix

adding lifecycle rule for logs bucket - artifacts-bucket-logs/

---

modules/integration/efs-on-eks/requirements-dev.txt
modules/integration/emr-to-opensearch/requirements.txt
modules/mlops/kubeflow-platform/requirements-dev.txt
modules/mlops/kubeflow-users/requirements-dev.txt
modules/post-processing/lane-detection/requirements-dev.txt
modules/post-processing/lane-detection/requirements.txt

Fixing requirements files maullay to set urllib3~=1.26.17 as per depenabot issues:
234
235
252
258
260
261

updating urllib3 to 1.26.17 manually - dependabot issues

---

CHANGELOG.md
modules/analysis/rosbag-image-pipeline/requirements-dev.txt

The pillow version needed updating in `analysis/rosbag-image-pipeline/requirements-dev.txt` to avert a vulnerabilty:
ref #264 and #265 in Security Issues

updating pillow version to 10.0.1

---

.github/workflows/gh-sync-cc.yaml

Change sync workflow to only trigger on pushes to branch `scene-intelligence-with-rosbag-on-aws`

chore: Change sync workflow trigger

---

modules/sensor-extraction/ros-to-png/stack.py

The ros-png module failed sonarqube due to having greater than 13 named parameters in stacky.py...this redices the number to 13

reducing named parameters

---

CHANGELOG.md
modules/integration/fsx-lustre-on-eks/README.md
modules/integration/fsx-lustre-on-eks/app.py
modules/integration/fsx-lustre-on-eks/stack_fsx_eks.py
modules/integration/fsx-lustre-on-eks/tests/test_app.py
modules/integration/fsx-lustre-on-eks/tests/test_stack.py

#415 
Adding ability to pass in storage capacity on fsx-lsutre-on-eks from the manifests

adding capacity configs for fsx-lustre-on-eks

---

CHANGELOG.md
modules/examples/docker-build/README.md
modules/examples/docker-build/deployspec.yaml
modules/examples/docker-build/modulestack.yaml

Refactoring `docker-build` module to be generic. 
NOTE: the only change from the original behaviour is ECR repository name used to be prefixed with seedkit name. I do not think this is required, but can change back to adhere to the same behaviour.

generify docker-build module

---

.github/ISSUE_TEMPLATE/missing_integ_tests_issue.md
.github/workflows/check-integration-tests.yml

- This workflow is intended to poll our repo and its modules and create issues in the backlog for any modules that do not have integration tests.
- In the future as modules are added this will assure we are tracking that modules get integration tests
- The workflow will run on a schedule, but can also be triggered manuallly

chore: adding workflow to check integration tests presence in modules

---

.github/workflows/check-integration-tests.yml

- update workflow to only run once a day to avoid intermittent rate limit issues with our other repos

chore: update workflow to only run once a day

---

.github/workflows/module-checks-dev-requirements-change.yml
CHANGELOG.md

- updated `get-modules` workflow to only run tests against changed files in `modules/**`
- adds workflow specific to changes for `requirements-dev.txt` so all static checks are run

chore: update module checks workflow

---

manifests/ros-image-demo/ros-image-demo-mwaa/docker-repository-modules.yaml
manifests/ros-image-demo/ros-image-demo-sfn/docker-repository-modules.yaml

- update ros-image-demo manifests to use latest ecr module

chore: update ros-image-demo manifests to use latest ecr module

---

manifests/robotic-training-on-eks/dcv-eks.yaml

- fix robotic-training-on-eks manifest module reference

chore: fix `robotic-training-on-eks` manifest module reference

---

CHANGELOG.md
manifests/ros-image-demo/ros-image-demo-sfn/aws-analysis-modules.yaml
modules/analysis/rosbag-image-pipeline-sfn/deployspec.yaml

Corrected the export of metadata in `autonomous-driving-data-framework/modules/analysis/rosbag-image-pipeline-sfn`

fix deployspec export of metadata in rosbag-sfn
