- manifests/example-dev/core-modules.yaml
- manifests/example-dev/ide-modules.yaml
- manifests/example-prod/ide-modules.yaml
Commented VSCode and Neptune modules manifests
> commented out few modules manifests

- docs/deployment_guide.md
- scripts/setup-secrets-example.sh
Related to ADDF issue in gitlab #14
Enforce check of installed jq, fail if not installed.
> enhance pwd seeding script, fail if jq not installed

- CHANGELOG.md
- README.md
Added the list of latest supported modules in the ADDF readme
> fixed readme

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Added details to the contributing guide.
> added details to the contributing guide

- CHANGELOG.md
- modules/analysis/rosbag-scene-detection/README.md
From awslabs - issue 30
Update README text in rosbag-scenet-detection
> edited text

- docs/deployment_guide.md
> Steps to update `ADDF`

- README.md
> fixed the broken readme link of scene detection pipeline

- modules/analysis/rosbag-scene-detection/README.md
- modules/analysis/rosbag-scene-detection/deployspec.yaml
The two ROSBag files were not yet publicly accessible.
Provide links that are publicly available.
> Fix S3 links of the sample ROSBag files.

- CHANGELOG.md
- modules/core/eks/deployspec.yaml
- modules/core/eks/modulestack.yaml
- modules/core/eks/stack.py
#32 
Added region modified to masterrole references
> resolving conflicts in roles for same account, different region

- docs/deployment_guide.md
fixed the incorrect arguement in the deployment docs
> fixed the incorrect arguement

- modules/analysis/rosbag-scene-detection/README.md
Add missing architecture diagram to README
> add scene detection architecture diagram

- modules/visualization/dev-instance/user-data/script.sh
The userscript modified not to update the .aws config on the filesystem
> remove the config file on creation...causes conflict

- modules/visualization/dev-instance/README.md
- modules/visualization/dev-instance/app.py
- modules/visualization/dev-instance/setup.py
- modules/visualization/dev-instance/stack.py
Adding multi-instance support
Updating the short description
> adding multi-instance support

- modules/sensor-extraction/ros-to-parquet/src/requirements.txt
*Issue #62 *
Added requests to autonomous-driving-data-framework/modules/sensor-extraction/ros-to-parquet/src/requirements.txt
> Added requests lib to requirements.txt in ros-to-parquet module

- requirements.txt
> chore: update seedfamer version

- modules/visualization/dev-instance/scripts/sample-layout.json
Add sample layout file for foxglove studio to dev instance scripts
> feat: add sample layout.json for foxglove studio to dev-instance scripts

- modules/mlops/kubeflow-platform/manage_admin_user.py
- modules/mlops/kubeflow-users/app.py
- modules/mlops/kubeflow-users/manage_kustomize_users.py
- modules/mlops/kubeflow-users/scripts/create_kf_user_secret.py
Performing static check to prep for merge to main
> prepping for static checks

- modules/mlops/kubeflow-platform/deployspec.yaml
- modules/mlops/kubeflow-platform/gpu/nvidia-plugin-configmap.yaml
Installing the Nvidia Plugin so GPU nodes can be utilized
> adding NVIDIA  GPU plugin via helm

- docs/deployment_guide.md
#76 
Cosmetic changes...no code changes
> fixing typos

- modules/demo-only/opensearch-proxy/README.md
#23 
Adding documentation to readme about passwords supported.
> adding notation about passwords

- modules/mlops/kubeflow-platform/install_role_irsa.sh
- modules/mlops/kubeflow-platform/policies/iam-profile-sa-policy.json
Scoped back permissions of service account role policy
> reducing scope of SA role permissions

- modules/mlops/kubeflow-platform/deployspec.yaml
- modules/mlops/kubeflow-platform/setup.py
- modules/mlops/kubeflow-users/setup.py
> updating based onPR reviews

- modules/mlops/kubeflow-platform/README.md
- modules/mlops/kubeflow-platform/deployspec.yaml
Parameterizing nvidia plugin version in deployspec
> parameterizing nvidia plugin version

- CHANGELOG.md
Adding references to wireframes for UI
> adding links to wireframes for ui

- CHANGELOG.md
> updating proper changelog

- modules/core/mwaa/requirements/requirements.txt
The MWAA requirements had a conflict...reverting for this branch only
> removing airflow requirements def

- modules/core/mwaa/requirements/requirements.txt
The requirements file for MWAA had conflicts when installing....
> fixing dependencies for rosbag pipelines

- CHANGELOG.md
- requirements.txt
Update the seed-farmer dependency version to latest minor releaase
> updating version of seed-farmer in requirements

- .github/workflows/main.yml
- CHANGELOG.md
- manifests/example-dev/core-modules.yaml
- manifests/example-prod/core-modules.yaml
- manifests/mlops/core-modules.yaml
- modules/core/eks/README.md
- modules/core/eks/addons-iam-policies/fsx-csi-iam.json
- modules/core/eks/stack.py
- modules/integration/fsx-lustre-on-eks/.gitignore
- modules/integration/fsx-lustre-on-eks/README.md
- modules/integration/fsx-lustre-on-eks/app.py
- modules/integration/fsx-lustre-on-eks/deployspec.yaml
- modules/integration/fsx-lustre-on-eks/modulestack.yaml
- modules/integration/fsx-lustre-on-eks/pyproject.toml
- modules/integration/fsx-lustre-on-eks/requirements.txt
- modules/integration/fsx-lustre-on-eks/setup.cfg
- modules/integration/fsx-lustre-on-eks/setup.py
- modules/integration/fsx-lustre-on-eks/stack_fsx_eks.py
#152 
- Added `Fsx-Lustre-on-EKS` module
- Modified `core-eks` to install the FSx Driver by default
> fsx eks support

- modules/core/fsx-lustre/modulestack.yaml
- modules/core/fsx-lustre/stack.py
> Removed old project name ref

- CHANGELOG.md
- modules/analysis/aws-batch-demo/stack.py
- modules/analysis/rosbag-image-pipeline/stack.py
- modules/analysis/rosbag-scene-detection/infrastructure/ecs_stack.py
- modules/analysis/rosbag-scene-detection/infrastructure/emr_orchestration/stack.py
- modules/analysis/rosbag-scene-detection/infrastructure/emr_trigger/stack.py
- modules/sensor-extraction/ros-to-parquet/stack.py
- modules/sensor-extraction/ros-to-png/stack.py
- modules/simulations/batch-managed/stack.py
- modules/simulations/k8s-managed/stack.py
- modules/visualization/dev-instance/stack.py
The following modules (stack.py) have had the Solution ID added to their stacks:
- analysis/aws-batch-demo/stack.py
- analysis/rosbag-image-pipeline/stack.py
- analysis/rosbag-scene-detection/infrastucture/ecs-stack.py
- analysis/rosbag-scene-detection/infrastucture/emr-orchestration/stack.py
- analysis/rosbag-scene-detection/infrastucture/emr-trigger/stack.py
- sensor-extraction/ros-to-parquet/stack.py
- sensor-extraction/ros-to-png/stack.py
- simulations/batch-managed/stack.py
- simulations/k8s-managed/stack.py
- vizualization/dev-instance/stack.py
> Adding Solution ID to select modules for tracking

- modules/core/aws-batch/app.py
- modules/core/aws-batch/stack.py
A PR #167 was issued and merged without formatting...this is just a formatting operation PR
> formatting code

- CHANGELOG.md
- requirements.txt
Update the version of seed-farmer to latest 2.6.0
> updating version of seedfarmer to latest

- modules/analysis/rosbag-scene-detection/infrastructure/ecs_stack.py
The bucket names and relative paths seemed reversed...correcting
> correcting glue s3 path

- modules/post-processing/yolo-object-detection/deployspec.yaml
> increase build size

- modules/analysis/rosbag-scene-detection/infrastructure/ecs_stack.py
- modules/post-processing/yolo-object-detection/deployspec.yaml
syncing rosbag across branches
> syncing rosbag across branches

- CHANGELOG.md
- modules/optionals/networking/app.py
- modules/optionals/networking/stack.py
Refactored networking module to create publi, private and isolated subnets and standardized some cdk changes
> refactored networking module to create isolated subnets:

- CHANGELOG.md
- modules/analysis/aws-batch-demo/requirements-dev.txt
- modules/analysis/rosbag-image-pipeline/requirements-dev.txt
- modules/core/fsx-lustre/requirements-dev.txt
- modules/sensor-extraction/ros-to-parquet/requirements-dev.txt
- modules/simulations/batch-managed/requirements-dev.txt
- modules/simulations/k8s-managed/requirements-dev.txt
Commenting out `requirements-dev.txt` entries referring to MWAA libraries due to security scan results.
> removing offending security libs

- CHANGELOG.md
- modules/core/eks/README.md
- modules/core/eks/docs/eks-isolated/eks-isolated-deployment.yaml
- modules/core/eks/docs/eks-isolated/eks-isolated-docker-replication.yaml
- modules/core/eks/docs/eks-isolated/eks-isolated-eksmanifest.yaml
- modules/core/eks/docs/eks-isolated/eks-isolated.md
- modules/core/eks/docs/eks-private/eks-private-eksmanifest.yaml
- modules/core/eks/docs/eks-private/eks-private.md
added docs on how to launch eks in private and isolated subnets
> added docs on how to launch eks in private and isolated subnets

- CHANGELOG.md
- modules/integration/ddb-to-opensearch/layers/requirements.txt
- modules/integration/emr-to-opensearch/layers/requirements.txt
The lambda layer dependencies did not align with the runtime...locking the urllib3 version
> refactoring due to lambda changes

- CHANGELOG.md
- modules/post-processing/yolo-object-detection/app.py
- modules/post-processing/yolo-object-detection/src/requirements.txt
Fix Object detection module...update the container image and install the proper libs
> syncing fix for Object detection

- CHANGELOG.md
- modules/post-processing/yolo-object-detection/app.py
- modules/post-processing/yolo-object-detection/src/requirements.txt
Fixing Object detection module and syncing 
> fixing object detection

- docs/configuration.md
- docs/onboarding_addon.md
*Issue #, if available:* Added docs for onboarding the EKS Addon and explaining the configuration files for EKS Addon. 
*Description of changes:* Added two files:
Deployment and configuration of Addons on EKS
How to onbord a new Addon. 
> Adding docs in the repos

- CHANGELOG.md
- manifests/mlops/kf-platform.yaml
- modules/mlops/kubeflow-platform/install_build.sh
Updating MLOps due to build image change
> updating mlops due to build image change

- CHANGELOG.md
- manifests/mlops/kf-platform.yaml
- modules/mlops/kubeflow-platform/install_build.sh
Updating modules due to changes to build image
> updating mlops

- scripts/setup-secrets-dockerhub.sh
fixed the condition check and added tracing
> fixed the condition check and added tracing

- .gitignore
- CHANGELOG.md
- modules/examples/example-tf/deployspec.yaml
- modules/examples/example-tf/main.tf
- modules/examples/example-tf/modules/s3/main.tf
- modules/examples/example-tf/variables.tf
- modules/examples/example-tf/vars/variables.tfvars
Fixes #228 
improved the example tf module
> improved the example tf module

- CHANGELOG.md
- modules/analysis/rosbag-image-pipeline/app.py
- modules/analysis/rosbag-image-pipeline/deployspec.yaml
- modules/analysis/rosbag-image-pipeline/image_dags/detect_scenes.py
- modules/analysis/rosbag-image-pipeline/image_dags/ros_image_pipeline.py
Fixes #239 
refactored rosbag image pipeline module to include scene detection workflow in the dag, standardized the inputs of the module 
> refactored rip module to include scene detection workflow in the rip dag

- CHANGELOG.md
- modules/post-processing/yolop-lane-detection/src/detect_lanes.py
> yolop lane det refactoring

- CHANGELOG.md
- manifests/aws-solutions/aws-analysis-modules.yaml
- manifests/aws-solutions/core-modules.yaml
- manifests/aws-solutions/deployment.yaml
- manifests/aws-solutions/docker-image-modules.yaml
- manifests/aws-solutions/integration-modules.yaml
- manifests/aws-solutions/optional-modules.yaml
- requirements.txt
added manifest files for AV/ADAS solution
> added manifest files for AV/ADAS solution

- CHANGELOG.md
- modules/integration/ddb-to-opensearch/lambda/index.py
Updating / syncing ddb-to-opensarch lambda refactoring
> syncing ddb-to-opensearch lambda

- CHANGELOG.md
- manifests/aws-solutions/core-modules.yaml
- modules/analysis/rosbag-image-pipeline/image_dags/ros_image_pipeline.py
- modules/analysis/rosbag-image-pipeline/requirements-dev.txt
rosbag image pipeline refactored to work with mwaa 2.6.3
> rosbag image pipeline refactored to work with mwaa 2.6.3

- modules/core/metadata-storage/modulestack.template
- modules/integration/ddb-to-opensearch/modulestack.template
- modules/integration/efs-on-eks/modulestack.template
- modules/integration/eks-to-opensearch/modulestack.template
- modules/integration/emr-to-opensearch/modulestack.template
- modules/integration/opensearch-tunnel/modulestack.template
- modules/optionals/datalake-buckets/modulestack.template
- modules/service-catalog/modulestack.template
fixed the naming schema for cookie cutter description of iam policy names
> fixed the invalid modulestack.template files

- manifests/aws-solutions/catalog-modules.yaml
- manifests/aws-solutions/integ/addf-modules.yaml
> uncommenting integ manifests

- manifests/aws-solutions/core-modules.yaml
- manifests/example-prod/core-modules.yaml
destroying OS module via input param
> destroying OS module via input param

- CHANGELOG.md
- modules/analysis/rosbag-image-pipeline/image_dags/detect_scenes.py
- modules/analysis/rosbag-image-pipeline/image_dags/ros_image_pipeline.py
The spark portion of the detect scenes was not respecting image-topics passed in
> refactored rip-module spark code to respect image-topics passed in

- modules/analysis/rosbag-image-pipeline/image_dags/detect_scenes.py
Adding UDF to the dag to remove spaces from the names
> adding space cleanup on the names

- CHANGELOG.md
- modules/demo-only/rosbag-webviz/deployspec.yaml
- modules/demo-only/rosbag-webviz/package.json
Updating rosbag-webviz cdk version
> updating cdk version

- manifests/aws-solutions/aws-analysis-modules.yaml
- manifests/aws-solutions/catalog-modules.yaml
- manifests/aws-solutions/core-modules.yaml
- manifests/aws-solutions/docker-image-modules.yaml
- manifests/aws-solutions/integration-modules.yaml
- manifests/aws-solutions/optional-modules.yaml
Update solution manifests to point to github branches
> update solution manifests to point to the branch

- manifests/aws-solutions/core-modules.yaml
> updating proper path

- CHANGELOG.md
- modules/analysis/rosbag-image-pipeline/deployspec.yaml
- modules/analysis/rosbag-image-pipeline/image_dags/ros_image_pipeline.py
- modules/analysis/rosbag-image-pipeline/tests/conftest.py
The boto calls in the dag will have the solution info if configured
> adding solution info to dag of rip

- CHANGELOG.md
- modules/analysis/rosbag-scene-detection/requirements.in
- modules/analysis/rosbag-scene-detection/requirements.txt
EMR-Launch needed update as EMR modified the necessary policies for creating a cluster..the version of emr-launch was updated to 2.0.1
> updating emr-launch version

- manifests/aws-solutions/integ/manifest-update.py
- This file is required by integration testing.
> chore: adding integration manifest generator file

- .viperlightignore
- manifests/aws-solutions/deployment.yaml
> chore: Fixing viperlight violation

- .viperlightignore
> chore: viperlight ignore

- .github/workflows/gh-sync-cc.yaml
> chore: update workflow username

- .viperlightignore
> viperlight ignore

- .viperlightignore
> chore: viperlight ignore regex attempt 4

- .viperlightignore
> chore: viperlight ignore regex attempt 5

- .viperlightignore
> chore: viperlight ignore regex attempt 6

- .viperlightignore
> chore: viperlight ignore regex attempt 7

- .viperlightignore
> viperlight ignore regex attempt 8

- .viperlightignore
> viperlight ignore regex attempt 9

- .viperlightignore
> viperlight ignore regex attempt 10

- .bandit
- .github/workflows/gh-sync-cc.yaml
> chore: bandit ignore

- modules/integration/ddb-to-opensearch/tests/test_app.py
> chore: Fixing test imports

- modules/integration/ddb-to-opensearch/tests/test_app.py
> chore: Docker test omission

- CHANGELOG.md
- modules/optionals/ecr/app.py
standardized ecr module outputs
> standardized ecr module outputs

- modules/optionals/ecr/README.md
> fix ecr readme

- CHANGELOG.md
- manifests/mlops/core-modules.yaml
- manifests/mlops/deployment.yaml
- manifests/mlops/kf-platform.yaml
- manifests/mlops/kf-users.yaml
- manifests/mlops/optional-modules.yaml
- modules/mlops/kubeflow-users/deployspec.yaml
- modules/mlops/kubeflow-users/kustomize/config.template
- modules/mlops/kubeflow-users/requirements.txt
- kubeflow-users module had issues with cdk version, and dex auth callbacks, this was updated
- kubeflow-platform example updated in mlops manifest to refer to newer kf version to match eks 1.25
> updating kubeflow support

- modules/sensor-extraction/ros-to-png/stack.py
Syncing from main - ros-to-png stack param fix
> syncing from main

- .github/workflows/gh-sync-cc.yaml
- deployment/build-open-source-dist.sh
- deployment/build-s3-dist.sh
- deployment/manifest.yaml
- deployment/scene-intelligence-with-rosbag-on-aws-create.template
- deployment/scene-intelligence-with-rosbag-on-aws-delete.template
- manifests/aws-solutions/aws-analysis-modules.yaml
- manifests/aws-solutions/catalog-modules.yaml
- manifests/aws-solutions/core-modules.yaml
- manifests/aws-solutions/docker-image-modules.yaml
- manifests/aws-solutions/integration-modules.yaml
- manifests/aws-solutions/optional-modules.yaml
added deployment dir, moved single click templates to deployment dir, and updated the references of single click templates accordingly
> chore: updated the folders structure to match prod codecommit repo

- modules/sensor-extraction/ros-to-png/app.py
- modules/sensor-extraction/ros-to-png/stack.py
- modules/sensor-extraction/ros-to-png/tests/test_stack.py
Reduce stack params...introduce a dict
> reduce the number of method params

- .github/workflows/gh-sync-cc.yaml
- deployment/build-s3-dist.sh
- deployment/scene-intelligence-with-rosbag-on-aws-create.template
- deployment/scene-intelligence-with-rosbag-on-aws-delete.template
- One Click Template updates to add Parameters for tag
- Updating workflow to sync `deployment` and `.github` directories
- Simplifying `build-s3-dist.sh` with vars for templates
> chore: one-click template updates

- modules/sensor-extraction/ros-to-png/app.py
- modules/sensor-extraction/ros-to-png/stack.py
- modules/sensor-extraction/ros-to-png/tests/test_stack.py
Updating reduction of stack params...syncing with main
> syncing ros-png reduce params

- manifests/aws-solutions/aws-analysis-modules.yaml
- manifests/aws-solutions/catalog-modules.yaml
- manifests/aws-solutions/core-modules.yaml
- manifests/aws-solutions/docker-image-modules.yaml
- manifests/aws-solutions/integration-modules.yaml
- manifests/aws-solutions/optional-modules.yaml
Releasing AWS Solution with tag SO0279-v1.0.0
> modify manifests to point to SO0279-v1.0.0 tag

- CHANGELOG.md
- README.md
- modules/optionals/ecr/deployspec.yaml
fixed the metadata output from ecr module
> chore: ecr module metadata

- CHANGELOG.md
- modules/demo-only/rosbag-webviz/deployspec.yaml
- modules/demo-only/rosbag-webviz/package.json
Updated cdk version to 2.110.0 for rosbag-webviz
> update cdk version to sync with other branches

- buildspec.yml
> fix: setting buildspec to 3.10

- .github/workflows/module-checks.yml
- modules/analysis/rosbag-image-pipeline/requirements-dev.txt
- pinning `pendulum` in `rosbag-image-pipeline`
- adding workflow checks for `py3.10`
> chore: pinning `pendulum` in `rosbag-image-pipeline` & adding workflow checks for `py3.10`

- modules/analysis/rosbag-image-pipeline/requirements-dev.txt
When dependabot updates the airflow version, some dependencies get messed up...fixing
> fix pendulum dependency

- CHANGELOG.md
- modules/analysis/rosbag-image-pipeline/requirements-dev.txt
- modules/simulations/batch-managed/requirements-dev.txt
- modules/simulations/k8s-managed/requirements-dev.txt
fixed security updates about `apache-airflow` version
> chore: fixed security updates about apache-airflow version

- CHANGELOG.md
- modules/integration/opensearch-tunnel/app.py
- modules/integration/opensearch-tunnel/deployspec.yaml
made os-tunnel module generic by importing seedfarmer project name
> chore: made os-tunnel module generic by importing seedfarmer project name

- modules/integration/opensearch-tunnel/app.py
- modules/integration/opensearch-tunnel/deployspec.yaml
- modules/integration/opensearch-tunnel/stack.py
- modules/integration/opensearch-tunnel/tests/test_app.py
- modules/integration/opensearch-tunnel/tests/test_stack.py
> chore: fixed the ostunnel expports

- modules/sensor-extraction/ros-to-parquet/deployspec.yaml
- modules/sensor-extraction/ros-to-png/deployspec.yaml
- update deployspec for sensor extraction modules
> fix: update deployspec for sensor extraction modules

- CHANGELOG.md
- modules/integration/ddb-to-opensearch/stack.py
- update lambda runtime in `ddb-to-os` module
> chore: update lambda runtime in `ddb-to-os` module

- CHANGELOG.md
- modules/ml-training/k8s-managed/app.py
- modules/ml-training/k8s-managed/configure_asgs.py
- modules/ml-training/k8s-managed/project.toml
- modules/ml-training/k8s-managed/setup.cfg
- modules/ml-training/k8s-managed/stack.py
- modules/ml-training/k8s-managed/tests/test_app.py
- modules/ml-training/k8s-managed/tests/test_stack.py
#418 
Removing the taint tag on the ASG, adding skeletons for pytest, bringing code up to standards
> removing taint tag on asg

- CHANGELOG.md
- manifests/ml-training-on-eks/core-modules.yaml
- manifests/ml-training-on-eks/deployment.yaml
- manifests/ml-training-on-eks/image-modules.yaml
- manifests/ml-training-on-eks/integration-modules.yaml
- manifests/ml-training-on-eks/optional-modules.yaml
- manifests/ml-training-on-eks/replicator-modules.yaml
- manifests/ml-training-on-eks/training-modules.yaml
> updating manifests with release branches

- README.md
Adding badges in the README for Integration Tests and Static Checks
> chore: Adding badges for Integration Tests and Static Checks

- CHANGELOG.md
typo in the version number - v3.3.0
> typo in the version number

- CHANGELOG.md
N/A
-  Changelog information fix
> CHANGELOG Fix

- CHANGELOG.md
> incorrect changelog

- modules/integration/fsx-lustre-on-eks/deployspec.yaml
> fix fsx-lustre-on-eks metadata export

- CHANGELOG.md
- modules/visualization/dev-instance-foxbox/app.py
- modules/visualization/dev-instance-foxbox/deployspec.yaml
- modules/visualization/dev-instance-foxbox/modulestack.yaml
- modules/visualization/dev-instance-foxbox/stack.py
> updating foxbox to be generic

- CHANGELOG.md
- modules/integration/ddb-to-opensearch/app.py
- modules/integration/ddb-to-opensearch/deployspec.yaml
- modules/integration/ddb-to-opensearch/stack.py
- modules/integration/ddb-to-opensearch/tests/test_app.py
- modules/integration/ddb-to-opensearch/tests/test_stack.py
Make `ddb-to-opensearch` module generic.
> generify `ddb-to-opensearch` module

- CHANGELOG.md
- modules/analysis/rosbag-image-pipeline-sfn/app.py
- modules/analysis/rosbag-image-pipeline/app.py
- modules/post-processing/yolo-object-detection/README.md
- modules/post-processing/yolo-object-detection/src/detect_objects.py
- modules/post-processing/yolo-object-detection/src/requirements.txt
Follow up to https://github.com/awslabs/autonomous-driving-data-framework/pull/477
- bump ultralytics to latest version
- update model to `yolov10s`
Some samples below:
*yolov10s:*
*yolov8s:*
*yolov5su:*
> update to YOLOv10

- CHANGELOG.md
- manifests/ml-training-on-eks/core-modules.yaml
- manifests/ml-training-on-eks/deployment.yaml
- manifests/ml-training-on-eks/image-modules.yaml
- manifests/ml-training-on-eks/integration-modules.yaml
- manifests/ml-training-on-eks/optional-modules.yaml
- manifests/ml-training-on-eks/replicator-modules.yaml
- modules/ml-training/training-image/mnist/README.md
- modules/ml-training/training-k8s-deployment/app.py
- modules/ml-training/training-k8s-deployment/modulestack.yaml
- modules/ml-training/training-k8s-deployment/project.toml
- modules/ml-training/training-k8s-deployment/stack.py
- requirements.txt
- fixed the permission issues.
> chore: ml-training-on-eks bugs

- CHANGELOG.md
- manifests/example-dev/core-modules.yaml
- manifests/example-dev/optional-modules.yaml
- manifests/ml-training-on-eks/core-modules.yaml
- manifests/ml-training-on-eks/image-modules.yaml
- manifests/ml-training-on-eks/optional-modules.yaml
- manifests/ml-training-on-eks/training-modules.yaml
updated manifests to reflect IDF versions
> updated manifests to reflect IDF versions

- docs/deployment_guide.md
- manifests/example-dev/core-modules.yaml
- manifests/example-dev/deployment.yaml
- manifests/example-dev/example-modules.yaml
- manifests/example-dev/optional-modules.yaml
- manifests/example-dev/replicator-modules.yaml
- requirements.txt
- update manifests to use latest IDF module versions
Related #575 
> chore: update manifests to use latest idf modules

- manifests/ml-training-on-eks/core-modules.yaml
- manifests/ml-training-on-eks/integration-modules.yaml
- manifests/ml-training-on-eks/optional-modules.yaml
- manifests/ml-training-on-eks/replicator-modules.yaml
- manifests/robotic-training-on-eks/buckets.yaml
- manifests/robotic-training-on-eks/core-modules.yaml
- manifests/robotic-training-on-eks/storage.yaml
- manifests/ros-image-demo/ros-image-demo-mwaa/core-modules.yaml
- manifests/ros-image-demo/ros-image-demo-mwaa/optional-modules.yaml
> chore: update idf module versions in manifests

- modules/analysis/rosbag-image-pipeline/requirements-dev.txt
Resolves [security alert](https://github.com/awslabs/autonomous-driving-data-framework/security/dependabot/414)
> chore: fix security alert Flaks-cors

- manifests/ml-training-on-eks/core-modules.yaml
- manifests/ml-training-on-eks/deployment.yaml
- manifests/ml-training-on-eks/integration-modules.yaml
- manifests/ml-training-on-eks/training-modules.yaml
- modules/ml-training/training-k8s-deployment/modulestack.yaml
- modules/ml-training/training-k8s-deployment/stack.py
- add fsx driver eks addon
- add missing manifest params
- fix modulestack permissions
Tested E2E: start step function execution and wait for the batch job to complete:
```
> kubectl logs -f pytorch-training-7c7795aa-4c58-4e71-aac6-63dac969df81-8nv2r -n training
torch.cuda.is_available()
True
Using CUDA
MNIST dataset found at: /data/fsx/import/FashionMNIST
is_distributed?
False
2024-09-04T20:37:32Z INFO     Train Epoch: 1 [0/60000 (0%)]     loss=2.2980
2024-09-04T20:37:32Z INFO     Train Epoch: 1 [640/60000 (1%)]   loss=2.3059
2024-09-04T20:37:33Z INFO     Train Epoch: 1 [1280/60000 (2%)]  loss=2.2698
2024-09-04T20:37:33Z INFO     Train Epoch: 1 [1920/60000 (3%)]  loss=2.2623
2024-09-04T20:37:33Z INFO     Train Epoch: 1 [2560/60000 (4%)]  loss=2.2693 …
```
> fix: `ml-training-on-eks` fsx & modulestack

- CHANGELOG.md
- modules/simulations/batch-managed/requirements-dev.txt
- modules/simulations/k8s-managed/requirements-dev.txt
- patching `apache-airflow` in simulations modules
> chore: Security Patch: 'apache-airflow'

- CHANGELOG.md
- manifests/example-dev/ide-modules.yaml
- modules/demo-only/jupyter-hub/deployspec.yaml
Related: #583 
- Add appropriate EKS admin role to demo manifest
- Removes `addf` hardcoded lines from deployspec
> fix: `jupyterhub` module

- CHANGELOG.md
- modules/simulations/batch-managed/requirements-dev.txt
- modules/simulations/k8s-managed/requirements-dev.txt
added security fixes based on dependabot alerts
> added security fixes

- CHANGELOG.md
- manifests/example-dev/core-modules.yaml
- manifests/example-dev/example-modules.yaml
- manifests/example-dev/optional-modules.yaml
- manifests/example-dev/replicator-modules.yaml
- manifests/ml-training-on-eks/core-modules.yaml
- manifests/ml-training-on-eks/integration-modules.yaml
- manifests/ml-training-on-eks/optional-modules.yaml
- manifests/ml-training-on-eks/replicator-modules.yaml
- manifests/robotic-training-on-eks/buckets.yaml
- manifests/robotic-training-on-eks/core-modules.yaml
- manifests/robotic-training-on-eks/storage.yaml
- manifests/ros-image-demo/ros-image-demo-mwaa/core-modules.yaml
- manifests/ros-image-demo/ros-image-demo-mwaa/docker-repository-modules.yaml
- manifests/ros-image-demo/ros-image-demo-mwaa/optional-modules.yaml
- manifests/ros-image-demo/ros-image-demo-sfn/docker-repository-modules.yaml
- manifests/visualization-on-eks/core-modules.yaml
- manifests/visualization-on-eks/integration-modules.yaml
- manifests/visualization-on-eks/optional-modules.yaml
- upgrade manifests to idf-modules `1.12.0`
> chore: upgrade manifests to idf 1.12.0

- CHANGELOG.md
- modules/analysis/rosbag-image-pipeline-sfn/app.py
- modules/analysis/rosbag-image-pipeline/app.py
- modules/post-processing/yolo-object-detection/src/detect_objects.py
- modules/post-processing/yolo-object-detection/src/requirements.txt
- update to [YOLO11](https://docs.ultralytics.com/models/yolo11/) object detection model
> feat: bump to yolo11 object detection model

- CHANGELOG.md
- modules/integration/opensearch-tunnel/README.md
- modules/integration/opensearch-tunnel/install_nginx.sh
https://github.com/awslabs/autonomous-driving-data-framework/issues/600
- fix `opensearch-tunnel` user data install script
- minor proofreading
*Testing:*
> fix: os tunnel user data install script

- CHANGELOG.md
- manifests/ros-image-demo/ros-image-demo-sfn/core-modules.yaml
- manifests/ros-image-demo/ros-image-demo-sfn/deployment.yaml
- manifests/ros-image-demo/ros-image-demo-sfn/docker-image-modules.yaml
- manifests/ros-image-demo/ros-image-demo-sfn/integration-modules.yaml
- manifests/ros-image-demo/ros-image-demo-sfn/optional-modules.yaml
Adding the tunnel and ddb trigger for indexing.
Updating manifests for latest code releases
> updating rosbag-image-pipeline-sfn to include tunnel

- CHANGELOG.md
- modules/analysis/rosbag-image-pipeline-sfn/requirements.txt
- modules/examples/eb-sf-batch/requirements.in
- modules/examples/eb-sf-batch/requirements.txt
- modules/examples/example-dags/requirements.txt
- modules/examples/example-spark-dags/requirements.in
- modules/examples/example-spark-dags/requirements.txt
The version of typing-extensions is older and needed to be updated. 
> update typing-extensions version
